services:
  location-database:
    image: 'redis:7.4.0'
    ports:
    - '6379:6379'
    environment:
    - REDIS_PASSWORD=${REDIS_PASSWORD}
    - REDIS_USER=${REDIS_USER}
    - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_DB_ADMIN_USERNAME}:${MONGO_DB_ADMIN_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    healthcheck:
      test: [ "CMD","mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
    tty: true
    stdin_open: true



  server:
    container_name: server
    image: eclipse-temurin:21-jdk-alpine
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
      - DATASOURCE_DATABASE=mudatabase
      - DATASOURCE_USERNAME=yourusername
      - DATASOURCE_PASSWORD=yourpassword
      - DATASOURCE_AUTHSOURCE=admin
    volumes:
        - ./server/build/libs/server-0.0.1.jar:/server.jar
    command: [ "java", "-jar", "/botalka.jar" ]
    restart: unless-stopped
    depends_on:
      - mongo
