services:
  location-database:
    image: 'redis:7.4.0'
    ports:
    - '6379:6379'
    environment:
    - REDIS_PASSWORD=${REDIS_PASSWORD}
    - REDIS_USER=${REDIS_USER}
    - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true



  server:
    container_name: server
    image: eclipse-temurin:21-jdk-alpine
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
      - DATASOURCE_DATABASE=mudatabase
      - DATASOURCE_USERNAME=yourusername
      - DATASOURCE_PASSWORD=yourpassword
      - DATASOURCE_AUTHSOURCE=admin
    volumes:
        - ./server/build/libs/server-0.0.1.jar:/server.jar
    command: [ "java", "-jar", "/botalka.jar" ]
    restart: unless-stopped
    depends_on:
      - mongo
