services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: testbase
      MONGO_DB_ADMIN_USERNAME: test
      MONGO_DB_ADMIN_PASSWORD: test
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8082:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: test
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://test:test@mongo:27017/testbase
      ME_CONFIG_BASICAUTH: false
    healthcheck:
      test: [ "CMD","mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
    tty: true
    stdin_open: true
    networks:
      - backend

  server:
    build: .
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - mongo
    environment:
      DB_USERNAME: test
      DB_PASSWORD: test
      DB_URL: mongodb://mongo:27017/testbase

volumes:
  mongo:

networks:
  backend:
