server:
    port: 8080
spring:
    data:
        mongodb:
            url: mongodb://mongo:mongo@mongo:27017/testbase?authSource=admin&replicaSet=rs0&?directConnection=true
            database: testbase
            authentication-database: admin
            replica-set-name: rs0

app:
    datasource:
        url: mongodb://mongo:27017
        db: testbase
        username: mongo
        password: mongo
        authSource: admin

api:
    prefix: /api/v1