server:
    port: 8080
    error:
        include-message: always

spring:
    data:
        mongodb:
            url: mongodb://mongo:mongo@mongo:27017/testbase?authSource=admin&replicaSet=rs0&?directConnection=true
            database: testbase
            authentication-database: admin
            replica-set-name: rs0

    jackson:
      property-naming-strategy: SNAKE_CASE

api:
    prefix: /api/v1
