server:
    port: 8888
spring:
    data:
        redis:
            database: 0
            host: "localhost"
            port: 6379
            username: ${REDIS_USER}
            password: ${REDIS_USER_PASSWORD}