server:
    port: 8888
spring:
    data:
        redis:
            database: 0
            host: "localhost"
            port: 6379
            username: ${REDIS_USER}
            password: ${REDIS_USER_PASSWORD}



        mongodb:
            database: maps
            replica-set-name: myReplicaSet

quarkus:
    mongodb:
        connection-string: mongodb://localhost:27017
    liquibase-mongodb:
        migrate-at-start: true
        change-log: db/changeLog.xml