server:
    port: 8080
spring:
    data:
        mongodb:
            url: mongodb://mongo:mongo@host.docker.internal:27017/test?authSource=admin&replicaSet=rs0
            database: testbase
            authentication-database: admin
            replica-set-name: rs0

app:
    datasource:
        url: mongodb://host.docker.internal:27017
        db: testbase
        username: mongo
        password: mongo
        authSource: admin

api:
    prefix: /api/v1